name: Package binaries and upload as artifacts

on: workflow_dispatch

jobs:

  release:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 30

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [16.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install Node.js, npm and yarn
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      
      # Install necessary system dependencies to compile on Linux
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libc6-dev-i386 gcc-multilib g++-multilib

      - name: Install minification modules globally
        run: npm install modclean minify-all node-prune --location=global

      - name: yarn install
        run: yarn install

      - name: Minify node_modules
        run: |
          modclean -n default:safe,default:caution -r
          node-prune
          minify-all

      - name: Build for OS
        run: yarn bundle

      - uses: actions/upload-artifact@v3
        with:
          name: electron-builder_artifacts
          path: dist/*.@(exe|AppImage|dmg)
