name: Package binaries and upload as artifacts

on: workflow_dispatch

jobs:

  release:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 30

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [16.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install Node.js, npm and yarn
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      
      # Install necessary system dependencies to compile on Linux
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libc6-dev-i386 gcc-multilib g++-multilib

      - name: Install minification modules globally
        run: npm install modclean minify-all node-prune --location=global

      - name: yarn install
        run: yarn install

      - name: Minify node_modules
        run: |
          modclean -n default:safe,default:caution -r
          node-prune
          minify-all

      - name: Build for OS
        run: yarn bundle

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'electron-builder.yml'
          propertyPath: 'appImage.artifactName'
          value: 'anotherkrunkerclient-Linux-Portable-Latest-${arch}.${ext}'
          commitChange: false
          updateFile: true

      - name: Build “latest” release
        run: |
          yarn add -D electron@^11
          yarn remove-dist-extras
          yarn electron-builder

      - uses: actions/upload-artifact@v3
        if: runner.os == 'Windows'
        with:
          name: Windows-Installer
          path: dist/*.exe
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: Linux-AppImage
          path: dist/*.AppImage
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        if: runner.os == 'macOS'
        with:
          name: macOS-Image
          path: dist/*.dmg
          if-no-files-found: error
