name: Build and package binaries, and upload as artifacts

on: workflow_dispatch

jobs:

  release:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 30

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [16.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install Node.js, npm and yarn
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      
      # Install necessary system dependencies to compile on Linux
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libc6-dev-i386 gcc-multilib g++-multilib

      - name: Install minification modules globally
        run: npm install modclean minify-all node-prune --location=global

      - name: yarn install
        run: yarn install

      - name: Minify node_modules
        run: |
          modclean -n default:safe,default:caution -r
          node-prune
          minify-all

      # Stable
      - name: Build stable binary
        run: |
          yarn bundle

      - name: Artifact stable Windows executable
        uses: actions/upload-artifact@v3
        if: runner.os == 'Windows'
        with:
          name: Windows-Installer-Stable
          path: dist/*.exe
          if-no-files-found: error

      - name: Artifact stable Linux AppImage
        uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: Linux-AppImage-Stable
          path: dist/*.AppImage
          if-no-files-found: error

      - name: Artifact stable macOS image
        uses: actions/upload-artifact@v3
        with:
          name: macOS-Image-Stable
          path: dist/*.@(exe|AppImage|dmg)
          if-no-files-found: error

      # Latest
      - name: Build latest binary
        run: |
          yarn add -D electron@^11
          yarn bundle

      - name: Artifact latest Windows executable
        uses: actions/upload-artifact@v3
        if: runner.os == 'Windows'
        with:
          name: Windows-Installer-Latest
          path: dist/*.exe
          if-no-files-found: error

      - name: Artifact latest Linux AppImage
        uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: Linux-AppImage-Latest
          path: dist/*.AppImage
          if-no-files-found: error

      - name: Artifact latest macOS image
        uses: actions/upload-artifact@v3
        with:
          name: macOS-Image-Latest
          path: dist/*.@(exe|AppImage|dmg)
          if-no-files-found: error
