name: Package binaries and upload as artifacts

on: workflow_dispatch

jobs:

  release:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 30

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [16.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install Node.js, npm and yarn
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      
      # Install necessary system dependencies to compile on Linux
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libc6-dev-i386 gcc-multilib g++-multilib

      - name: Build electron app binary
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # package.json script to call before electron-builder compiles
          build_script_name: 'bundle:gh-actions'

      - uses: actions/upload-artifact@v3
        if: runner.os == 'Windows' && env.IS_RELEASE
        with:
          name: Windows-Installer
          path: dist/*.exe
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        if: runner.os == 'Linux' && env.IS_RELEASE
        with:
          name: Linux-AppImage
          path: dist/*.AppImage
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        if: runner.os == 'macOS' && env.IS_RELEASE
        with:
          name: macOS-Image
          path: dist/*.dmg
          if-no-files-found: error
