name: Build packaged binaries

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install g++-multilib
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install g++-multilib

      - name: Setup build environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Target Windows
        if: matrix.os == 'windows-latest'
        run: yarn bundle:windows
        env: 
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Target Linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn bundle:linux
        env: 
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Target MacOS
        if: matrix.os == 'macos-latest'
        run: yarn bundle:darwin
        env: 
          GH_TOKEN: ${{ secrets.github_token }}
