name: Build packaged binaries

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install g++-multilib
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install g++-multilib

      - name: Setup build environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Target Windows
        if: matrix.os == 'windows-latest'
        run: yarn bundle:windows
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Installer
          path: dist/*.exe
          if-no-files-found: error


      - name: Target Linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn bundle:linux
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v3
        with:
          name: Linux-AppImages
          path: dist/*.AppImage
          if-no-files-found: error

      - name: Target MacOS
        if: matrix.os == 'macos-latest'
        run: yarn bundle:darwin
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v3
        with:
          name: MacOS-Image
          path: dist/*.dmg
          if-no-files-found: error

